// Copyright (c) 2026 Weave Thinker Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * Pure DOM-preservation planning helpers for the streaming markdown renderer
 * (StreamMarkdown.vue). Import-free — safe to unit-test in Node via type
 * stripping.
 *
 * Why this exists: StreamMarkdown re-renders the growing markdown buffer every
 * ~80ms while streaming. A naive `v-html` replacement destroys and re-creates
 * every node, which aborts in-flight `<img>` fetches — the image never loads
 * during the stream and only appears after refresh (conv ba74a7f5 repro).
 * The fix preserves live nodes across render passes: an `<img>` with an
 * identical signed src, and rendered mermaid/echarts blocks keyed by their
 * `data-mermaid-id` / `data-echarts-id`, are adopted into the new tree instead
 * of being re-created.
 */

/** Node kinds the renderer preserves. */
export type LiveNodeKind = 'img' | 'mermaid' | 'echarts'

export interface LiveNodeDesc {
  kind: LiveNodeKind
  /** img: the full src attribute; mermaid/echarts: the data-*-id value. */
  key: string
}

export interface FreshNodeDesc {
  kind: LiveNodeKind
  key: string
}

/**
 * Compute the adoption plan: for each fresh node (document order), the index
 * of the live node it should be replaced by, or -1 when nothing matches.
 *
 * Matching rules:
 *  - kind + key must both be equal (an img src never matches a block id)
 *  - empty keys never match
 *  - live nodes are consumed in document order — one live node can never be
 *    adopted by two fresh nodes (duplicate images match positionally)
 */
export function planNodeAdoption(
  live: LiveNodeDesc[],
  fresh: FreshNodeDesc[],
): number[] {
  const buckets = new Map<string, number[]>()
  live.forEach((n, i) => {
    if (!n.key) return
    const bucketKey = `${n.kind}\u0000${n.key}`
    const arr = buckets.get(bucketKey)
    if (arr) arr.push(i)
    else buckets.set(bucketKey, [i])
  })
  const plan: number[] = new Array(fresh.length).fill(-1)
  fresh.forEach((n, i) => {
    if (!n.key) return
    const arr = buckets.get(`${n.kind}\u0000${n.key}`)
    if (arr && arr.length > 0) {
      plan[i] = arr.shift() as number
    }
  })
  return plan
}

/**
 * Should a failed image (complete && naturalWidth===0 — e.g. the referenced
 * file did not exist yet when the markdown arrived) retry its fetch now?
 *
 * A failed img is still preserved across renders (no per-render request
 * spam), but its src is reset on a throttle so a file that appears later in
 * the stream (generated by a subsequent tool call) loads live without a
 * refresh. `force` bypasses the throttle — used on the final flush.
 */
export function shouldRetryFailedImg(
  now: number,
  lastRetryAt: number,
  force: boolean,
  intervalMs: number,
): boolean {
  if (force) return true
  if (lastRetryAt === 0) return true
  return now - lastRetryAt >= intervalMs
}
